name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial permission for pushing tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git Tag
        run: |
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}
